spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

ticket:
  invoice:
    policy:
      keywords:
        - "pr"
        - "-pr"
        - "ir"
        - "-ir"
        - "peru rail"
        - "perurail"
        - "inca rail"
        - "incarail"
    validation:
      enabled: true

google:
  drive:
    application-name: spring-drive-app
    credentials:
      location: classpath:credentials/pupe-advance-credential.json
    scopes:
      - https://www.googleapis.com/auth/drive.readonly

logging:
  level:
    root: INFO
    com.christiancanari.pupe: INFO
    org.apache.pdfbox: ERROR
    com.google.api.client: ERROR
